name: Deploy Project
on:
    pull_request:
        types:
            - opened
        branches:
            - 'main'
            - 'dev-*' # Single asteric means match any other except slashes
            - 'feature/**'  # Double asteric means match anyother plus an other slashes
    workflow_dispatch:
    push:
        branches:
            - 'main'
            - 'dev-*' # Single asteric means match any other except slashes
            - 'feature/**'  # Double asteric means match anyother plus an other slashes
        paths-ignore:
            - '.github/workflows/*'
jobs:
  test: # 1st Job Name
    runs-on: ubuntu-latest  # Enviroment
    steps:
      - name: Get Code
        uses: actions/checkout@v4 

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Project Dependencies
        run: cd GitHub_Actions/01_gh_actions_react_app && npm ci # 

      - name: Run test
        run: cd GitHub_Actions/01_gh_actions_react_app && npm test

  deploy: # 2nd Job Name
    needs: test # you can specify multipe jobs i.e [job1, job2, job3]
    runs-on: ubuntu-latest  # Enviroment
    steps:
      - name: Get Code
        uses: actions/checkout@v4 

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Project Dependencies
        run:  npm ci # 

      - name: Build Project
        run:  npm run build

      - name: Deploy
        run: echo "Deploying project... "
